window.InterviewProQuestionCatalog = {
  additionalQuestionRanges: {
    'algorithms/graphs': [[399, 401]],
    'architecture/distributed': [[371, 380]],
    'architecture/messaging': [[381, 388]],
    'architecture/scenarios': [[408, 418]],
    'architecture/service_patterns': [[402, 407]],
    'databases/querying': [[389, 393], [436, 436]],
    'databases/scaling': [[394, 398], [432, 432]],
    'golang/backend': [[326, 339]],
    'golang/build_security': [[367, 370], [431, 431]],
    'golang/collections_deep': [[243, 248]],
    'golang/concurrency_patterns': [[272, 280], [434, 435]],
    'golang/context_deep': [[308, 313], [315, 315]],
    'golang/design': [[340, 345]],
    'golang/errors': [[261, 271]],
    'golang/generics': [[299, 307]],
    'golang/language': [[184, 202]],
    'golang/optimization': [[351, 366]],
    'golang/runtime_deep': [[289, 298]],
    'golang/runtime_internals': [[346, 350]],
    'golang/synchronization': [[281, 288]],
    'golang/testing': [[316, 325], [433, 433]],
    'golang/types': [[249, 260]],
    'reliability/resilience': [[419, 423]]
  },
  clarificationCounts: {
    'algorithms/graphs': 3,
    'architecture/messaging': 8,
    'architecture/scenarios': 11,
    'architecture/security': 4,
    'architecture/service_patterns': 6,
    'architecture/services': 11,
    'databases/indexes': 24,
    'databases/postgresql': 30,
    'databases/querying': 6,
    'databases/redis': 23,
    'databases/scaling': 6,
    'databases/sql': 27,
    'golang/basics': 22,
    'golang/build_security': 1,
    'golang/concurrency': 44,
    'golang/concurrency_patterns': 2,
    'golang/language': 19,
    'golang/runtime': 25,
    'golang/testing': 1,
    'linux/kernel': 9,
    'linux/memory': 12,
    'linux/processes': 19,
    'network/http': 4,
    'network/transport': 6,
    'reliability/observability': 7,
    'reliability/resilience': 5
  },
  questions: [
    {"id":1,"topic":"reliability/sre","title":"Что такое подход Blameless Post-Mortem и почему в SRE культуре не ищут «виновного» в инциденте?"},
    {"id":2,"topic":"reliability/sre","title":"Что такое SLA, SLO и SLI? Как понять, что сервис деградирует до того, как клиенты пожалуются?"},
    {"id":3,"topic":"containers/delivery","title":"В чем концептуальная разница между GitOps (werf, Argo CD) и классическим пушем из пайплайна (CI/CD push)?"},
    {"id":4,"topic":"linux/kernel","title":"Что такое контейнер глазами ядра Linux? Существует ли контейнер как объект ядра и как взаимодействуют namespaces, cgroups, pivot_root и capabilities?"},
    {"id":5,"topic":"linux/processes","title":"Какими способами можно посмотреть файлы, открытые процессом?"},
    {"id":6,"topic":"linux/processes","title":"В какой директории лежат файловые дескрипторы запущенного процесса?"},
    {"id":7,"topic":"linux/processes","title":"Можно ли в приложении перехватывать сигнал SIGKILL?"},
    {"id":8,"topic":"linux/processes","title":"Процессы в каком статусе нельзя завершить сигналом SIGKILL?"},
    {"id":9,"topic":"linux/kernel","title":"Что такое Load Average? О чем говорит ситуация, когда LA высокий, а утилизация CPU низкая?"},
    {"id":10,"topic":"linux/kernel","title":"df -h показывает 50% свободного места, но при попытке создать файл возникает ошибка 'No space left on device'. В чем причина и как проверить?"},
    {"id":11,"topic":"linux/memory","title":"Как работает OOM Killer в Linux и на основе чего ядро выбирает, какой процесс принудительно завершить (oom_score, oom_score_adj)?"},
    {"id":12,"topic":"linux/processes","title":"Что происходит при удалении открытого процессами файла через rm? Освободится ли место на диске сразу?"},
    {"id":13,"topic":"linux/processes","title":"В чем разница между жесткими (hard links) и символическими (symlinks) ссылками на уровне файловой системы и inode?"},
    {"id":14,"topic":"linux/processes","title":"Как работают системные вызовы fork и execve, и что такое оптимизация Copy-on-Write (CoW)?"},
    {"id":15,"topic":"linux/kernel","title":"Что делать при переполнении таблицы nf_conntrack в логах ядра ('nf_conntrack: table full, dropping packet')?"},
    {"id":16,"topic":"linux/kernel","title":"Что такое cgroups v1 vs v2, и какие проблемы с лимитами памяти/CPU возникали в старых версиях контейнеров на cgroups v1?"},
    {"id":17,"topic":"linux/processes","title":"Что такое зомби (defunct) процессы и сироты (orphan), чем они опасны и как их корректно утилизировать?"},
    {"id":18,"topic":"linux/memory","title":"Как устроена виртуальная память в Linux (Virtual Memory, RSS, Swap, Page Faults)?"},
    {"id":19,"topic":"linux/memory","title":"Что такое страница памяти?"},
    {"id":20,"topic":"linux/processes","title":"Что такое сисколл?"},
    {"id":21,"topic":"linux/kernel","title":"Какие знаешь примитивы синхронизации в ОС?"},
    {"id":22,"topic":"linux/kernel","title":"Что такое user space и kernel space? Зачем нужно такое разделение?"},
    {"id":23,"topic":"linux/processes","title":"Что такое файловый дескриптор?"},
    {"id":24,"topic":"linux/memory","title":"На голом сервере запущен сервис с утечкой памяти. Что произойдет, когда память закончится?"},
    {"id":25,"topic":"linux/processes","title":"Чем отличается процесс от системного потока?"},
    {"id":26,"topic":"linux/kernel","title":"Команда top показывает, что процесс потребляет 146% CPU. Что это означает?"},
    {"id":27,"topic":"linux/processes","title":"Как убить процесс linux'e?"},
    {"id":28,"topic":"linux/memory","title":"Что такое TLB и когда помогают HugePages?"},
    {"id":29,"topic":"network/kubernetes","title":"Жизнь сетевого пакета в Kubernetes (Life of a Packet): как проходит запрос от внешнего клиента через DNS, Ingress, Service ClusterIP, iptables/eBPF до сетевого неймспейса пода и обратно?"},
    {"id":30,"topic":"network/transport","title":"Чем отличается UDP от TCP?"},
    {"id":31,"topic":"network/transport","title":"Как узнать MAC-адрес у публичного DNS-сервера 8.8.8.8?"},
    {"id":32,"topic":"network/transport","title":"Как на одном порту запустить два приложения?"},
    {"id":33,"topic":"network/transport","title":"Что может поменяться в IP-пакете при прохождении маршрутизатора без NAT?"},
    {"id":34,"topic":"network/transport","title":"Что будет с UDP-пакетом, если он больше, чем MTU?"},
    {"id":35,"topic":"network/kubernetes","title":"Что происходит по шагам, когда сервис внутри Kubernetes делает запрос к other-service.default.svc.cluster.local?"},
    {"id":36,"topic":"network/transport","title":"В чем разница между состояниями TCP сокетов TIME_WAIT и CLOSE_WAIT? О какой ошибке в коде приложения говорит накопление CLOSE_WAIT?"},
    {"id":37,"topic":"network/transport","title":"Что такое MTU Blackhole и почему в оверлейных сетях Kubernetes (VXLAN, Geneve, Calico, Cilium) часто снижают MTU (например, до 1450)?"},
    {"id":38,"topic":"network/kubernetes","title":"В чем разница между реализациями сетевого прокси в Kubernetes: iptables vs IPVS vs eBPF (Cilium)?"},
    {"id":39,"topic":"network/kubernetes","title":"В кластере K8s внезапно подскочили задержки DNS-запросов. В чем суть проблемы ndots:5 в /etc/resolv.conf?"},
    {"id":40,"topic":"network/http","title":"В чем разница между кодами ошибок 502 Bad Gateway и 504 Gateway Timeout на Ingress/Nginx? Как их диагностировать?"},
    {"id":41,"topic":"network/transport","title":"Что такое TCP Keep-Alive и SO_REUSEPORT, для чего они применяются в высоконагруженных сетевых сервисах?"},
    {"id":42,"topic":"network/transport","title":"Как работает протокол BGP и MetalLB / Cilium BGP Control Plane для анонсирования адресов сервисов LoadBalancer в локальной сети?"},
    {"id":43,"topic":"network/transport","title":"Чем различаются протоколы TCP и UDP?"},
    {"id":44,"topic":"network/http","title":"В чем разница между proxy / reverse-proxy?"},
    {"id":45,"topic":"network/transport","title":"Как BitTorrent доставляет данные поверх UDP, если UDP не гарантирует доставку?"},
    {"id":46,"topic":"network/http","title":"Чем HTTP/3 и QUIC отличаются от HTTP/2 поверх TCP?"},
    {"id":47,"topic":"network/http","title":"Когда статические файлы стоит отдавать с отдельного домена?"},
    {"id":48,"topic":"network/http","title":"Чем HTTP/1.1 отличается от HTTP/2?"},
    {"id":49,"topic":"network/http","title":"Что означают HTTP-ответы 100 Continue и 301 Moved Permanently?"},
    {"id":50,"topic":"containers/delivery","title":"Путь от Git Push до продакшена (Zero Downtime GitOps): как устроен полный цикл сборки, тестирования, безопасной доставки через werf и раскатки в Kubernetes?"},
    {"id":51,"topic":"containers/docker","title":"Какие практики для уменьшения размера docker-образа существуют?"},
    {"id":52,"topic":"containers/docker","title":"Что такое контейнер под капотом Linux? Какие механизмы ядра (namespaces, cgroups, chroot/pivot_root) обеспечивают изоляцию?"},
    {"id":53,"topic":"containers/docker","title":"В чем проблема PID 1 в контейнере? Почему сигналы (SIGTERM) могут игнорироваться и почему возникают процессы-зомби?"},
    {"id":54,"topic":"containers/docker","title":"Чем отличаются инструкции ENTRYPOINT и CMD в Dockerfile, и в чем разница между exec-формой и shell-формой?"},
    {"id":55,"topic":"containers/docker","title":"Чем отличаются Container Runtime Interface (CRI), containerd, CRI-O и OCI runc?"},
    {"id":56,"topic":"containers/docker","title":"Какие практики безопасности Dockerfile и контейнеров обязательны для production (non-root, read-only rootfs, drop capabilities)?"},
    {"id":57,"topic":"containers/docker","title":"Как устроен кэш слоев в Docker и как оптимизировать Dockerfile для ускорения CI/CD сборки в разы?"},
    {"id":58,"topic":"containers/delivery","title":"Что такое Pod Security Standards (PSS / PSA) и какими директивами в SecurityContext ограничивают привилегии контейнера?"},
    {"id":59,"topic":"containers/delivery","title":"В чем отличие стратегий деплоя Blue-Green, Canary и RollingUpdate? Какие риски и преимущества у каждой?"},
    {"id":60,"topic":"containers/delivery","title":"Что такое Immutable Infrastructure (неизменяемая инфраструктура) и почему запрещено вносить ручные правки на серверах через SSH?"},
    {"id":61,"topic":"kubernetes/architecture","title":"Анатомия развертывания: что происходит по шагам в кластере с момента 'kubectl apply -f deployment.yaml' до готовности пода отвечать на трафик?"},
    {"id":62,"topic":"kubernetes/operations","title":"Почему namespace может висеть в статусе Terminating?"},
    {"id":63,"topic":"kubernetes/architecture","title":"Зачем нужен Kubelet?"},
    {"id":64,"topic":"kubernetes/architecture","title":"Какие механизмы позволяют управлять размещением pod по узлам?"},
    {"id":65,"topic":"kubernetes/architecture","title":"Какой компонент kubernetes хранит состояние ресурсов кластера?"},
    {"id":66,"topic":"kubernetes/architecture","title":"Какой ресурс kubernetes нужен, чтобы экземпляры pod запустились на всех нодах кластера?"},
    {"id":67,"topic":"kubernetes/architecture","title":"Какой механизм используется в kubernetes для написания своих собственных scheduler’ов?"},
    {"id":68,"topic":"kubernetes/architecture","title":"В каком порядке выполняются admission hooks и почему?"},
    {"id":69,"topic":"kubernetes/operations","title":"Как проверить права пользователя на действия в кластере, несмотря на RoleBinding?"},
    {"id":70,"topic":"kubernetes/operations","title":"В чем разница между StartupProbe, LivenessProbe и ReadinessProbe? Что произойдет, если зафейлится Readiness, а что — если Liveness?"},
    {"id":71,"topic":"kubernetes/architecture","title":"Как устроен etcd в Kubernetes? Что такое кворум и что произойдет с кластером из 3 master-нод, если откажут 1 нода или 2 ноды?"},
    {"id":72,"topic":"kubernetes/operations","title":"Как происходит Graceful Shutdown пода при обновлении Deployment (RollingUpdate)? Какова роль preStop hook, SIGTERM и задержки удаления из Endpoints?"},
    {"id":73,"topic":"kubernetes/operations","title":"Под завис в статусе CrashLoopBackOff, OOMKilled или Pending. Как по шагам диагностировать причину для каждого статуса?"},
    {"id":74,"topic":"kubernetes/architecture","title":"Что такое Kubernetes Operator pattern? Из каких компонентов он состоит (CRD, Reconcile loop, Informers, WorkQueue)?"},
    {"id":75,"topic":"kubernetes/operations","title":"В чем разница между Resource Requests и Limits в Kubernetes, и как они транслируются в cgroups (cpu.shares, cfs_quota, memory.limit)?"},
    {"id":76,"topic":"kubernetes/operations","title":"Нода Kubernetes перешла в статус NotReady. Каков пошаговый алгоритм диагностики на самой ноде и через kube-apiserver?"},
    {"id":77,"topic":"kubernetes/operations","title":"Как безопасно управлять секретами в Kubernetes при использовании GitOps (Vault, External Secrets Operator, SOPS, Sealed Secrets)?"},
    {"id":78,"topic":"kubernetes/operations","title":"Как работают Horizontal Pod Autoscaler (HPA) и Vertical Pod Autoscaler (VPA), и почему их опасно использовать одновременно по метрике CPU/Memory?"},
    {"id":79,"topic":"kubernetes/operations","title":"Что такое Finalizers в Kubernetes и как они могут заблокировать удаление ресурсов?"},
    {"id":80,"topic":"kubernetes/architecture","title":"В чем разница между традиционным Ingress-контроллером и Kubernetes Gateway API?"},
    {"id":81,"topic":"databases/distributed","title":"Что такое Quorum и какие есть алгоритмы консенсуса?"},
    {"id":82,"topic":"databases/postgresql","title":"Как организовать High Availability (HA) для PostgreSQL в Kubernetes? (Patroni, DCS/etcd, streaming replication, VIP/PgBouncer)?"},
    {"id":83,"topic":"databases/postgresql","title":"Что такое Write-Ahead Log (WAL) и checkpoints в реляционных СУБД, и зачем они нужны для надежности данных?"},
    {"id":84,"topic":"databases/distributed","title":"Как устроен CSI (Container Storage Interface) в Kubernetes? Чем отличаются режимы доступа ReadWriteOnce (RWO) и ReadWriteMany (RWX)?"},
    {"id":85,"topic":"databases/distributed","title":"Что такое проблема Split-Brain в распределенных системах и кластерах баз данных, и как от нее защититься?"},
    {"id":86,"topic":"databases/postgresql","title":"СУБД PostgreSQL внезапно встала в Read-Only. Какие возможные инфраструктурные причины (заполнение диска WAL, XID wraparound, потеря лидера Patroni)?"},
    {"id":87,"topic":"databases/postgresql","title":"Что такое Transaction ID Wraparound в PostgreSQL и почему жизненно необходим автовакуум (autovacuum)?"},
    {"id":88,"topic":"databases/redis","title":"Как устроен Redis под капотом (single-threaded event loop, RDB snapshot vs AOF log)?"},
    {"id":89,"topic":"databases/distributed","title":"Чем синхронная репликация отличается от асинхронной и полусинхронной, и в чем компромисс между производительностью и надежностью (RPO/RTO)?"},
    {"id":90,"topic":"databases/sql","title":"Что такое транзакция? Какие уровни изоляции транзакций существуют в РСУБД?"},
    {"id":91,"topic":"databases/sql","title":"Какие аномалии могут быть при параллельном исполнении транзакций?"},
    {"id":92,"topic":"databases/postgresql","title":"Какие типы локов (блокировок) есть в PostgreSQL? Кто берет эти локи?"},
    {"id":93,"topic":"databases/postgresql","title":"Что такое MVCC в PostgreSQL?"},
    {"id":94,"topic":"databases/postgresql","title":"Зачем PostgreSQL нужен VACUUM и чем отличается VACUUM FULL?"},
    {"id":95,"topic":"databases/indexes","title":"Что делает индекс и какую цену за него платит запись?"},
    {"id":96,"topic":"databases/indexes","title":"Есть ли в PostgreSQL постоянно поддерживаемый кластерный индекс?"},
    {"id":97,"topic":"databases/indexes","title":"Чем EXPLAIN ANALYZE отличается от EXPLAIN?"},
    {"id":98,"topic":"databases/postgresql","title":"Зачем приложению пул соединений с PostgreSQL?"},
    {"id":99,"topic":"databases/sql","title":"Что произойдёт, если строка нарушит CHECK в PostgreSQL?"},
    {"id":100,"topic":"databases/sql","title":"Может ли табличный CHECK сравнивать несколько столбцов?"},
    {"id":101,"topic":"databases/sql","title":"Как NULL влияет на сравнения и агрегаты в SQL?"},
    {"id":102,"topic":"databases/sql","title":"Как ORDER BY сортирует по нескольким полям?"},
    {"id":103,"topic":"databases/sql","title":"Почему большая пагинация через OFFSET замедляется?"},
    {"id":104,"topic":"databases/postgresql","title":"Зачем выполнять ANALYZE после крупного изменения данных?"},
    {"id":105,"topic":"databases/indexes","title":"Когда применяют REINDEX?"},
    {"id":106,"topic":"databases/indexes","title":"Что делает CLUSTER и почему его эффект не постоянен?"},
    {"id":107,"topic":"databases/indexes","title":"Какие риски у ALTER TABLE на большой таблице?"},
    {"id":108,"topic":"databases/indexes","title":"Чем CREATE INDEX CONCURRENTLY отличается от обычного создания?"},
    {"id":109,"topic":"databases/indexes","title":"Что учитывают при DROP INDEX CONCURRENTLY?"},
    {"id":110,"topic":"databases/sql","title":"Чем TRUNCATE отличается от DELETE в PostgreSQL?"},
    {"id":111,"topic":"databases/sql","title":"Когда использовать DELETE вместо TRUNCATE?"},
    {"id":112,"topic":"databases/sql","title":"Что возвращает UPDATE ... RETURNING?"},
    {"id":113,"topic":"databases/postgresql","title":"Что делает autovacuum?"},
    {"id":114,"topic":"databases/postgresql","title":"Что показывает SHOW ALL?"},
    {"id":115,"topic":"databases/postgresql","title":"Как pg_stat_activity помогает найти долгий запрос?"},
    {"id":116,"topic":"databases/postgresql","title":"Как найти блокирующую сессию через pg_locks?"},
    {"id":117,"topic":"databases/postgresql","title":"Когда использовать pg_cancel_backend и pg_terminate_backend?"},
    {"id":118,"topic":"reliability/observability","title":"В чем разница между Pull-моделью (Prometheus) и Push-моделью сбора метрик? Каковы плюсы и минусы каждой?"},
    {"id":119,"topic":"reliability/observability","title":"Что такое проблема High Cardinality (высокой кардинальности) меток в Prometheus и как она способна вызвать OOM на сервере мониторинга?"},
    {"id":120,"topic":"reliability/observability","title":"В чем разница между логами (Loki/Elasticsearch/ClickHouse), метриками (Prometheus/VictoriaMetrics) и трейсами (OpenTelemetry/Jaeger)? Когда нужны трейсы?"},
    {"id":121,"topic":"reliability/sre","title":"Что такое правило четырех золотых сигналов (Four Golden Signals) в Google SRE (Latency, Traffic, Errors, Saturation)?"},
    {"id":122,"topic":"reliability/observability","title":"Как устроена архитектура Prometheus Operator и что такое Custom Resources ServiceMonitor и PodMonitor?"},
    {"id":123,"topic":"golang/basics","title":"Как преобразовать строку в число в Go?"},
    {"id":124,"topic":"golang/basics","title":"Какой функцией стандартной библиотеки нужно воспользоваться для извлечения ошибки конкретного типа?"},
    {"id":125,"topic":"golang/runtime","title":"Планировщик какого семейства используется в go?"},
    {"id":126,"topic":"golang/runtime","title":"Сколько горутин может единовременно выполняться на логическом процессоре в go?"},
    {"id":127,"topic":"golang/basics","title":"В каком варианте преобразования типа возможна паника и какая конструкция позволяет её избежать?"},
    {"id":128,"topic":"golang/basics","title":"Для чего нужен механизм seed в структурах map?"},
    {"id":129,"topic":"golang/concurrency","title":"Что такое утечка горутин (goroutine leak), как ее обнаружить с помощью pprof и как предотвратить в коде?"},
    {"id":130,"topic":"golang/concurrency","title":"Как устроен и зачем нужен пакет context в Go? Как передавать отмену и таймауты при работе с HTTP/gRPC и Kubernetes API?"},
    {"id":131,"topic":"golang/concurrency","title":"Чем небуферизованный канал отличается от буферизованного, и что произойдет при чтении/записи/закрытии nil канала или уже закрытого канала?"},
    {"id":132,"topic":"golang/basics","title":"Как устроен слайс под капотом (структура slice header) и по какому алгоритму растет capacity при использовании append?"},
    {"id":133,"topic":"golang/concurrency","title":"В чем разница между sync.Mutex и sync.RWMutex? Почему мьютекс нельзя передавать по значению (копировать)?"},
    {"id":134,"topic":"golang/ecosystem","title":"Что такое client-go и controller-runtime? Как устроен Reconciler loop при написании собственных утилит или операторов для Kubernetes?"},
    {"id":135,"topic":"golang/concurrency","title":"Как реализовать паттерн Worker Pool на горутинах и каналах для параллельной обработки пачки задач с ограничением конкурентности?"},
    {"id":136,"topic":"golang/runtime","title":"Как устроен детектор гонок (Race Detector) в Go (go test -race) и как он находит гонки данных во время выполнения?"},
    {"id":137,"topic":"golang/runtime","title":"Как устроен сборщик мусора (Garbage Collector) в Go (трехцветный триколорный алгоритм, фазы STW, влияние GOGC и GOMEMLIMIT)?"},
    {"id":138,"topic":"golang/ecosystem","title":"Как правильно протестировать функцию, взаимодействующую с внешним API или Kubernetes, с помощью интерфейсов и моков?"},
    {"id":139,"topic":"golang/runtime","title":"В чем разница между стеком и кучей (stack vs heap) в Go, и как компилятор принимает решение об Escape Analysis (go build -gcflags='-m')?"},
    {"id":140,"topic":"golang/runtime","title":"Что такое GOMAXPROCS? Зачем это нужно?"},
    {"id":141,"topic":"golang/runtime","title":"pprof. Что это такое и зачем нужно?"},
    {"id":142,"topic":"golang/basics","title":"Что такое интерфейс в Go? Как он устроен внутри (iface / eface)?"},
    {"id":143,"topic":"golang/concurrency","title":"Чем горутины отличаются от потоков?"},
    {"id":144,"topic":"golang/basics","title":"Что такое замыкание? Приведите пример использования замыкания."},
    {"id":145,"topic":"golang/concurrency","title":"Что такое mutex и зачем он нужен?"},
    {"id":146,"topic":"golang/concurrency","title":"Что такое каналы? Зачем нужны?"},
    {"id":147,"topic":"golang/basics","title":"Что такое слайс? Как он устроен?"},
    {"id":148,"topic":"golang/basics","title":"Что из себя представляет строка в Go?"},
    {"id":149,"topic":"golang/runtime","title":"Как устроен планировщик Go: G, M, P и work stealing?"},
    {"id":150,"topic":"golang/basics","title":"Как устроена map в современных версиях Go?"},
    {"id":151,"topic":"golang/concurrency","title":"Как select выбирает операции над каналами?"},
    {"id":152,"topic":"golang/concurrency","title":"Зачем нужен context.Context и что в нём передавать?"},
    {"id":153,"topic":"golang/basics","title":"Когда вычисляются аргументы defer и в каком порядке выполняются вызовы?"},
    {"id":154,"topic":"golang/runtime","title":"Как Go GC находит и освобождает недоступные объекты?"},
    {"id":155,"topic":"golang/concurrency","title":"Чем отличаются sync.Once и sync.Pool?"},
    {"id":156,"topic":"golang/concurrency","title":"Когда выбирать sync.Mutex, а когда sync.RWMutex?"},
    {"id":157,"topic":"golang/concurrency","title":"Чем гонка данных отличается от deadlock?"},
    {"id":158,"topic":"golang/concurrency","title":"Что проверяет go test -race и чего детектор не гарантирует?"},
    {"id":159,"topic":"golang/runtime","title":"Что делает runtime.Gosched()?"},
    {"id":160,"topic":"golang/concurrency","title":"Как канал Go хранит ожидающих отправителей и получателей?"},
    {"id":161,"topic":"golang/concurrency","title":"Как отличить нулевое значение из канала от чтения после закрытия?"},
    {"id":162,"topic":"golang/runtime","title":"Почему выделение на стеке обычно дешевле выделения в куче?"},
    {"id":163,"topic":"golang/basics","title":"Почему порядок обхода map в Go нельзя считать постоянным?"},
    {"id":164,"topic":"golang/concurrency","title":"Что происходит при чтении, записи и закрытии nil-канала?"},
    {"id":165,"topic":"golang/basics","title":"Чем rune отличается от byte при работе со строками Go?"},
    {"id":166,"topic":"golang/runtime","title":"Что происходит с памятью стека после возврата из функции Go?"},
    {"id":167,"topic":"architecture/services","title":"В чем разница между REST и RPC подходами?"},
    {"id":168,"topic":"architecture/services","title":"Что представляет собой протокол HTTP? Из каких основных частей состоят HTTP-запрос и ответ?"},
    {"id":169,"topic":"reliability/observability","title":"Какие существуют инструменты для мониторинга и отладки микросервисов?"},
    {"id":170,"topic":"architecture/services","title":"Какие вопросы обсудить при использовании Kafka между сервисами?"},
    {"id":171,"topic":"reliability/observability","title":"Как работают распределённые трассировки, например Jaeger?"},
    {"id":172,"topic":"databases/redis","title":"Как сделать очередь задач на Redis и не потерять работу при сбое воркера?"},
    {"id":173,"topic":"databases/redis","title":"Для каких задач подходит Redis?"},
    {"id":174,"topic":"databases/redis","title":"Когда кеш помогает и как измерить его пользу?"},
    {"id":175,"topic":"databases/redis","title":"Как избежать рассинхронизации кеша и базы данных?"},
    {"id":176,"topic":"databases/redis","title":"Почему Redis быстро обслуживает много соединений?"},
    {"id":177,"topic":"databases/redis","title":"Как безопасно задать ключ блокировки в Redis?"},
    {"id":178,"topic":"databases/redis","title":"Что делает INCRBY?"},
    {"id":179,"topic":"databases/redis","title":"Как EXPIRE управляет временем жизни ключа?"},
    {"id":180,"topic":"databases/redis","title":"Что означают результаты TTL?"},
    {"id":181,"topic":"databases/redis","title":"Почему KEYS опасен на большой базе и чем заменить?"},
    {"id":182,"topic":"architecture/security","title":"Как хранить пароли так, чтобы усложнить перебор?"},
    {"id":183,"topic":"architecture/security","title":"Когда нужно сравнение за постоянное время?"},
    ...(window.InterviewProAdditionalQuestions || [])
  ],
  relatedGroups: [
    [1, 2, 121],
    [1, 120, 169, 171],
    [2, 118, 119, 121, 122],
    [5, 6, 23],
    [5, 12, 13, 23],
    [7, 8, 17, 27, 53],
    [10, 12, 13],
    [14, 17, 25, 22],
    [20, 22, 23],
    [11, 18, 19, 24, 28, 75],
    [9, 26, 75, 78],
    [15, 29, 37, 38],
    [16, 4, 52, 75],
    [21, 133, 145, 156, 157],
    [30, 43, 45, 46],
    [31, 33, 42, 29],
    [32, 41, 44],
    [34, 37, 29],
    [36, 41, 72],
    [40, 44, 80],
    [46, 48, 49, 168],
    [47, 48, 49],
    [29, 35, 38, 39, 42],
    [15, 37, 38, 39],
    [3, 50, 59, 60, 61, 72],
    [51, 57, 50],
    [4, 52, 16, 55, 56, 58],
    [7, 17, 53, 72],
    [54, 53, 56],
    [55, 63, 52],
    [61, 63, 64, 65, 66, 67, 68, 70],
    [64, 66, 67, 78],
    [65, 71, 81],
    [62, 79, 74],
    [69, 68, 77],
    [70, 72, 73, 78],
    [73, 75, 76, 11],
    [74, 134, 79],
    [80, 29, 40],
    [84, 55, 61],
    [81, 71, 82, 85, 89],
    [82, 83, 86, 89, 98],
    [83, 87, 93, 94, 113],
    [90, 91, 92, 93],
    [99, 100, 101, 112],
    [102, 103, 97],
    [95, 97, 104, 108],
    [96, 105, 106],
    [107, 108, 109],
    [103, 95, 97],
    [110, 111, 112],
    [114, 115, 116, 117, 92],
    [98, 115, 117],
    [88, 176, 173, 181],
    [172, 170, 135],
    [174, 175, 179, 180],
    [177, 81, 85],
    [178, 179, 180],
    [123, 127, 148, 165],
    [124, 127, 142, 138],
    [128, 150, 163],
    [132, 147, 139, 162, 166],
    [144, 153, 139],
    [129, 130, 152, 135, 143],
    [131, 146, 151, 160, 161, 164],
    [133, 145, 156, 157, 158, 136],
    [155, 133, 145],
    [125, 126, 140, 149, 159],
    [136, 157, 158],
    [137, 154, 139, 162, 166],
    [141, 129, 137],
    [134, 74, 138],
    [167, 168, 44, 46, 48],
    [170, 172, 135],
    [182, 183, 77],
    [118, 119, 122, 121],
    [120, 169, 171, 141]
  ]
};
